name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules

      - name: Install NPM
        run: npm install
        
      - name: Lint
        run: npm run lint
        
      - name: Run tests
        run: npm test
